### ISSUE TITLE
meningotype can not work

### ISSUE THREAD

**Issue by chen1i6c04** [MDU-PHL/meningotype#35]
Hi
I installed ```meningotype v0.8.4``` with ```pip``` and tried to run it, and show the error:
```
Traceback (most recent call last):
  File "/home/chen1i6c04/miniconda3/envs/meningotype/bin/meningotype", line 8, in <module>
    sys.exit(main())
  File "/home/chen1i6c04/miniconda3/envs/meningotype/lib/python3.6/site-packages/meningotype/meningotype.py", line 438, in main
    check_db_files(porA1alleles, porA1URL)
  File "/home/chen1i6c04/miniconda3/envs/meningotype/lib/python3.6/site-packages/meningotype/meningotype.py", line 97, in check_db_files
    update_db(f, db_url)
  File "/home/chen1i6c04/miniconda3/envs/meningotype/lib/python3.6/site-packages/meningotype/meningotype.py", line 88, in update_db
    urllib.urlretrieve(db_url, db_file)
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```
Did I take any mistake?

Thanks

**Comment by tseemann** [comment]
`AttributeError: module 'urllib' has no attribute 'urlretrieve'`

This seems like the wrong version of a module is being used.

@abcdtree @andersgs @kristyhoran 
Is the conda recipe for this allow a library that is too new?

**Comment by andersgs** [comment]
I think that is an overhang from Py2. In py3, urtlib was incorporated into the standard library, but divided into sub modules. I think the function is now under `urllib.requests`.

**Comment by andersgs** [comment]
Actually, the more correct interpretation is that `urllib` got a significant overhaul in py3. I am trying to look at this. Should be trivial to fix.

**Comment by andersgs** [comment]
@chen1i6c04 please update to version v0.8.5, thank you.

**Comment by chen1i6c04** [comment]
@andersgs it can work, thanks
