### ISSUE TITLE
User can't run --update if installed globally

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/meningotype#6]
Check permissions first for `--db` folder ?   (or catch exception)
Allow local DB in `$HOME/.config/` ?

```
% meningotype  --updatedb

Updating "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/meningotype/db/PorA_VR1.fas" ...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/meningotype", line 11, in <module>
    load_entry_point('meningotype==0.4b0', 'console_scripts', 'meningotype')()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/meningotype/meningotype.py", line 327, in main
    update_db(porA1alleles, porA1URL)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/meningotype/meningotype.py", line 77, in update_db
    os.rename(db_file, db_file+'.old')
OSError: [Errno 13] Permission denied
```

**Comment by kwongj** [comment]
Closed #6.
