### ISSUE TITLE
error in menwy.py with non-P/G/S amino acid in EX7E motif

### ISSUE THREAD

**Issue by kwongj** [MDU-PHL/meningotype#9]
If the amino acid at position 310 is not P(W), G(Y) or S(W/Y), it generates a key error:

```
Traceback (most recent call last):
  File "/home/jasonk1/scripts/bin/meningotype", line 11, in <module>
    load_entry_point('meningotype==0.7b0', 'console_scripts', 'meningotype')()
  File "/home/jasonk1/.local/lib/python2.7/site-packages/meningotype/meningotype.py", line 459, in main
    seroCOUNT = '/'.join(seroTYPE(f, seroPRIMERS, allelesDB))
  File "/home/jasonk1/.local/lib/python2.7/site-packages/meningotype/meningotype.py", line 138, in seroTYPE
    sero = seroWY(f, sero)
  File "/home/jasonk1/.local/lib/python2.7/site-packages/meningotype/meningotype.py", line 144, in seroWY
    wyTYPE = menwy.menwy(f, False)
  File "/home/jasonk1/.local/lib/python2.7/site-packages/meningotype/menwy.py", line 61, in menwy
    serogroup = seroDICT[EX7E[3]]
KeyError: 'F'
```

**Comment by kwongj** [comment]
For now, reports these as the PCR serotype e.g. detected through synG etc.
The amino acid sequence of the motif can be found by running `menwy.py`.
